//CLIENTS
export const GET_CLIENTS = 'GET_CLIENTS';
export const POST_CLIENT = 'POST_CLIENT';
//CLIENTS TYPES
export const GET_CLIENT_TYPES = 'GET_CLIENT_TYPES';
export const POST_TYPECLIENT = 'POST_TYPECLIENT';
//CXC
export const GET_ALL_CXC = 'GET_ALL_CXC';
export const POST_CXCABONO = 'POST_CXCABONO';
