//SUPPLIERS
export const GET_SUPPLIERS = 'GET_SUPPLIERS';
export const POST_SUPPLIERS = 'POST_SUPPLIERS';
//SUPPLIERS TYPES
export const GET_SUPPLIERS_TYPES = 'GET_SUPPLIERS_TYPES';
export const POST_SUPPLIERS_TYPES = 'POST_SUPPLIERS_TYPES';
//SUPLIERS CXP
export const GET_ALL_CXP = 'GET_ALL_CXP';
export const POST_CXP = 'POST_CXP';